using System;
using Aspose.Words;
using Aspose.Words.Saving;

class HighResolutionTiffExample
{
    static void Main()
    {
        // Create a new blank document.
        Document doc = new Document();

        // Add some sample content.
        DocumentBuilder builder = new DocumentBuilder(doc);
        builder.Writeln("This is a high‑resolution TIFF image generated by Aspose.Words.");

        // Initialize ImageSaveOptions for TIFF format.
        ImageSaveOptions saveOptions = new ImageSaveOptions(SaveFormat.Tiff);

        // Set both horizontal and vertical DPI to 600.
        // The Resolution property sets both values simultaneously.
        saveOptions.Resolution = 600f;
        // Alternatively, you could set them individually:
        // saveOptions.HorizontalResolution = 600f;
        // saveOptions.VerticalResolution = 600f;

        // Save the document as a TIFF image with the specified resolution.
        doc.Save("HighResolutionOutput.tiff", saveOptions);
    }
}
