using System;
using System.IO;
using System.Net.Http;
using Aspose.Words;
using Aspose.Words.Saving;

class Program
{
    static void Main()
    {
        // Paths to the local source document and the final PDF output.
        const string existingDocPath = "Existing.docx";
        const string outputPdfPath = "CombinedEncrypted.pdf";

        // Load the existing DOCX from the file system.
        Document existingDoc = new Document(existingDocPath);

        // Download the DOCX generated by the web service.
        byte[] webDocBytes = DownloadDocumentBytes("https://example.com/template.docx");

        // Load the downloaded DOCX from a memory stream.
        using (MemoryStream webStream = new MemoryStream(webDocBytes))
        {
            Document webDoc = new Document(webStream);

            // Append the web‑generated document to the end of the existing document,
            // preserving the source formatting.
            existingDoc.AppendDocument(webDoc, ImportFormatMode.KeepSourceFormatting);
        }

        // Configure PDF encryption: user password, owner password and desired permissions.
        PdfEncryptionDetails encryption = new PdfEncryptionDetails(
            userPassword: "UserPass123",
            ownerPassword: "OwnerPass123",
            permissions: PdfPermissions.ModifyAnnotations | PdfPermissions.Printing);

        // Create PDF save options and assign the encryption details.
        PdfSaveOptions pdfOptions = new PdfSaveOptions
        {
            EncryptionDetails = encryption
        };

        // Save the combined document as an encrypted PDF.
        existingDoc.Save(outputPdfPath, pdfOptions);
    }

    // Helper method to synchronously download a document as a byte array.
    static byte[] DownloadDocumentBytes(string url)
    {
        using (HttpClient client = new HttpClient())
        {
            // For brevity we use .Result; in production code prefer async/await.
            HttpResponseMessage response = client.GetAsync(url).Result;
            response.EnsureSuccessStatusCode();
            return response.Content.ReadAsByteArrayAsync().Result;
        }
    }
}
