using System;
using System.IO;
using System.Net.Http;
using Aspose.Words;
using Aspose.Words.Loading;
using Aspose.Words.Saving;

class AppendAndEncryptPdf
{
    static void Main()
    {
        // Path to the existing DOCX file on disk.
        string existingDocPath = @"C:\Docs\Template.docx";

        // URL of the REST API that returns a DOCX file.
        string apiUrl = "https://example.com/api/document";

        // Password that will protect the resulting PDF.
        string pdfPassword = "SecretPassword";

        // Load the existing document from the file system.
        Document existingDoc = new Document(existingDocPath);

        // Download the DOCX generated by the REST API.
        byte[] apiDocBytes = DownloadDocumentBytes(apiUrl).GetAwaiter().GetResult();

        // Load the downloaded DOCX into an Aspose.Words Document using a memory stream.
        using (MemoryStream apiStream = new MemoryStream(apiDocBytes))
        {
            Document apiDoc = new Document(apiStream);

            // Append the API document to the end of the existing document.
            existingDoc.AppendDocument(apiDoc, ImportFormatMode.KeepSourceFormatting);
        }

        // Set up PDF encryption details (user password, no owner password, default permissions).
        PdfEncryptionDetails encryption = new PdfEncryptionDetails(pdfPassword, string.Empty);

        // Configure PDF save options to use the encryption details.
        PdfSaveOptions pdfOptions = new PdfSaveOptions
        {
            EncryptionDetails = encryption
        };

        // Save the combined document as an encrypted PDF.
        string outputPdfPath = @"C:\Docs\CombinedEncrypted.pdf";
        existingDoc.Save(outputPdfPath, pdfOptions);
    }

    // Helper method to download a document from a REST endpoint.
    private static async System.Threading.Tasks.Task<byte[]> DownloadDocumentBytes(string url)
    {
        using (HttpClient client = new HttpClient())
        {
            HttpResponseMessage response = await client.GetAsync(url);
            response.EnsureSuccessStatusCode();
            return await response.Content.ReadAsByteArrayAsync();
        }
    }
}
