using System;
using System.IO;
using System.Xml;
using Aspose.Pdf;

class Program
{
    static void Main()
    {
        // Paths for the source PDF, the XML data and the resulting PDF.
        const string pdfPath      = "source.pdf";
        const string xmlPath      = "data.xml";
        const string outputPdf    = "updated.pdf";

        // Ensure the input files exist.
        if (!File.Exists(pdfPath))
        {
            Console.Error.WriteLine($"PDF not found: {pdfPath}");
            return;
        }
        if (!File.Exists(xmlPath))
        {
            Console.Error.WriteLine($"XML not found: {xmlPath}");
            return;
        }

        // Load the XML document into memory.
        XmlDocument xmlDoc = new XmlDocument();
        xmlDoc.Load(xmlPath);

        // Example modification: change the value of the first <Title> element.
        XmlNode titleNode = xmlDoc.SelectSingleNode("//Title");
        if (titleNode != null)
        {
            titleNode.InnerText = "Updated Title at " + DateTime.Now;
        }

        // Example modification: add a new <Comment> element under the root.
        XmlElement commentElem = xmlDoc.CreateElement("Comment");
        commentElem.InnerText = "Generated by Aspose.Pdf on " + DateTime.Now;
        xmlDoc.DocumentElement?.AppendChild(commentElem);

        // Bind the modified XML to the PDF and save the result.
        using (Document pdfDoc = new Document(pdfPath))
        {
            // Convert the modified XmlDocument to a memory stream.
            using (MemoryStream xmlStream = new MemoryStream())
            {
                xmlDoc.Save(xmlStream);
                xmlStream.Position = 0; // Reset stream position for reading.

                // Bind the XML (and optional XSL) to the PDF.
                pdfDoc.BindXml(xmlStream);
            }

            // Save the updated PDF.
            pdfDoc.Save(outputPdf);
        }

        Console.WriteLine($"PDF saved with updated XML content to '{outputPdf}'.");
    }
}