using System;
using System.IO;
using System.Net;
using System.Net.Mail;
using Aspose.Words;
using Aspose.Words.Saving;

namespace AsposeWordsEmailExample
{
    class Program
    {
        static void Main()
        {
            // -----------------------------------------------------------------
            // 1. Create a simple Word document using Aspose.Words.
            // -----------------------------------------------------------------
            Document doc = new Document();                     // create a blank document (lifecycle rule)
            DocumentBuilder builder = new DocumentBuilder(doc);
            builder.Writeln("Hello, this is a test document generated by Aspose.Words.");
            builder.Writeln("It will be saved as MHTML and sent as an email attachment.");

            // -----------------------------------------------------------------
            // 2. Save the document as an MHTML file.
            //    Use the Save(string, SaveFormat) overload (lifecycle rule).
            // -----------------------------------------------------------------
            string mhtmlPath = Path.Combine(Path.GetTempPath(), "TestDocument.mht");
            doc.Save(mhtmlPath, SaveFormat.Mhtml);            // save as MHTML (lifecycle rule)

            // -----------------------------------------------------------------
            // 3. Create an email message and attach the MHTML file.
            // -----------------------------------------------------------------
            MailMessage message = new MailMessage();
            message.From = new MailAddress("sender@example.com");   // replace with actual sender
            message.To.Add("recipient@example.com");               // replace with actual recipient
            message.Subject = "Test Email with MHTML Attachment";
            message.Body = "Please find the attached MHTML document.";

            // Attach the MHTML file.
            Attachment attachment = new Attachment(mhtmlPath, "application/octet-stream");
            attachment.Name = "TestDocument.mht";
            message.Attachments.Add(attachment);

            // -----------------------------------------------------------------
            // 4. Configure the SMTP client and send the email.
            // -----------------------------------------------------------------
            SmtpClient smtpClient = new SmtpClient
            {
                Host = "smtp.example.com",        // replace with your SMTP server
                Port = 587,                       // common port for TLS
                EnableSsl = true,
                Credentials = new NetworkCredential("smtp_user", "smtp_password") // replace with credentials
            };

            try
            {
                smtpClient.Send(message);
                Console.WriteLine("Email sent successfully.");
            }
            catch (SmtpException ex)
            {
                Console.WriteLine($"SMTP error: {ex.StatusCode} - {ex.Message}");
            }
            finally
            {
                // Clean up temporary MHTML file.
                if (File.Exists(mhtmlPath))
                {
                    File.Delete(mhtmlPath);
                }

                // Dispose objects.
                attachment.Dispose();
                message.Dispose();
                smtpClient.Dispose();
            }
        }
    }
}
